# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs


name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        
      - name: Install deps
        run: |
          if [ -f package-lock.json ]; then npm ci; else npm install; fi

      - name: Lint
        run: npm run lint --if-present

      - name: Test
        run: npm test --if-present --silent

      - name: Build
        run: npm run build --if-present
      - name: Deploy
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: 217.160.36.240
          username: root
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd /root
            ./cd.sh test https://github.com/RDFormations/testCI
  
